import {
    GET_ROOM_FAILURE,
    GET_ROOM_START,
    GET_ROOM_SUCCESS,
    INIT_FAILURE,
    INIT_START,
    INIT_SUCCESS,
    MOVE_FAILURE,
    MOVE_START,
    MOVE_SUCCESS
} from '../actions/types';
